### ISSUE TITLE
Windows client stuck on "Loading..."

### ISSUE THREAD

**Issue by ghost** [sagivo/StockStalk#1]
After install its stuck at 'Loading...' just after signing in on my newly created Robinhood account. Closing & relaunching the app has no effect. 

I tried to report this using both a reply from my "Windows is ready" email, as well as the Contact link at the button of the website, both of which returned a mailer daemon message undeliverable message.

**Comment by ghost** [comment]
Apparently that's what happens when the Robinhood account has yet to be verified. A few minutes later I get an email about being approved, & now the issue is gone.

**Comment by sagivo** [comment]
Happy to hear you got it figured. Feel free to update the readme with this info so others will know
