### ISSUE TITLE
Windows- Version 0.0.7 shows wrong version number in app

### ISSUE THREAD

**Issue by ghost** [sagivo/StockStalk#3]
The app's version number is displayed under the 'Settings' dialog, & shows it as being version #0.0.8, when I just installed 0.0.7.
![screenshot_20180308_215505](https://user-images.githubusercontent.com/8769067/37188074-6118d98e-231b-11e8-8e2d-ea3c6a497078.png)

**Comment by sagivo** [comment]
That's actually a good thing. The software was updated behind the scenes for you as we just released version 8.
