### ISSUE TITLE
Quantity shown as dollar, when app currently shows number of shares

### ISSUE THREAD

**Issue by monty-dev** [sagivo/StockStalk#5]
On the orders page, quantity value is shown as a dollar amount when app is actually showing the number of shares. Either the dollar sign should be removed over a TOTAL COST column included that is quantity x price. 

Order | Symbol | Type | Quantity | Price | Fees | Actions
-- | -- | -- | -- | -- | -- | --
sell | BPMX | stop | $1,704.00 | $0.30 | 0.00 | cancel

**Comment by sagivo** [comment]
great find @monteledwards !
fixed in https://github.com/sagivo/StockStalk/commit/12cdb33c515da6180653bb2cae448ebda373fcd6
thank you.
